### ISSUE TITLE
NEX Extension showing up blank 

### ISSUE THREAD

**Issue by benerz** [neonexchange/nex-extension-alpha#27]
Hello and good day team!
The NEX extension has been working fine until today, it is showing up a blank white page now.  I re-downloaded the google browser, cleared the cache and also reinstalled the Nex extension via. your suite on your site. still showing blank white.
![screen shot 2018-04-24 at 1 33 56 pm](https://user-images.githubusercontent.com/38678983/39165244-d709ca8e-47c6-11e8-960b-801e0fa5f05a.png)

Please help me, and thank you again for the things you guys are trying to do.

**Comment by Adeee212** [comment]
I am having the same issue. I suspect it may have to do with the new version of google chrome. I agreed to update google chrome and afterwards it started showing up blank. Thanks NEX team.

**Comment by Plutoniumweddingring** [comment]
I have the same issue. re-installing did not help and I cannot login to the extension now. any solutions for this problem?

**Comment by mojojojo2018** [comment]
I encountered the same issue yesterday and it seems to have not changed as of today yet. I have yet to submit my KYC documents for round 2, I hope this gets resolved before that ends!

**Comment by localhuman** [comment]
The problem has been fixed, it should be resolved if you re-start Chrome.

**Comment by lindafutshane** [comment]
I have uninstalled NEX, cleared cache, restarted my laptop and reinstalled NEX but there problem still persists. 
Please help

**Comment by Nitsirk86** [comment]
Same with me. Only blank, so I cannot submit my KYC... Help please

**Comment by lindafutshane** [comment]
@localhuman I have restarted chrome (chrome://restart) but this has made no difference.

**Comment by evgenyboxer** [comment]
This has now been fixed, restarting chrome (on Mac please ensure to quit the app from the top navbar) / your computer or via chrome://restart should do it.

**Comment by lindafutshane** [comment]
Thank you @evgenyboxer I am now able to login and have completed my KYC

**Comment by benerz** [comment]
Yes Thank you @evgenyboxer its working
